"""
Copyright (c) 2020 ARS Computer & Consulting GmbH

This program and the accompanying materials are made
available under the terms of the Eclipse Public License 2.0
which is available at https://www.eclipse.org/legal/epl-2.0/

SPDX-License-Identifier: EPL-2.0
"""

import abc

class ResourceLoader(abc.ABC):
    """
    The interface for a resource management plugin.
    """

    # getters of basic metadata
    @staticmethod
    @abc.abstractmethod
    def getManufacturer():
        """
        Get the manufacturer's name.
        
        Returns:
            str: Manufacturer's name.
        """

        raise NotImplementedError("Not implemented function")

    @staticmethod
    @abc.abstractmethod
    def getAuthor():
        """
        Get the author's name.
        
        Returns:
            str: Author's name.
        """

        raise NotImplementedError("Not implemented function")

    @staticmethod
    @abc.abstractmethod
    def getName():
        """
        Get the name of this plugin.
        !!! Should be identical for every plugin under same manufacturer !!!
        
        Returns:
            str: Name of this plugin.
        """

        raise NotImplementedError("Not implemented function")

    @staticmethod
    @abc.abstractmethod
    def getVersion():
        """
        Get the version of this plugin.
        
        Returns:
            str: Version of this plugin.
        """

        raise NotImplementedError("Not implemented function")

    @staticmethod
    @abc.abstractmethod
    def getDescription():
        """
        Get the description of this plugin.
        !!! 
            This is a description for helping average users to choose plugins with. 
            Make sure to make the content as easy and clear as possible. 
        !!!
        
        Returns:
            str: Description of this plugin.
        """

        raise NotImplementedError("Not implemented function")

    @staticmethod
    @abc.abstractmethod
    def getPriceDescription():
        """
        Get the price description of this plugin.
        !!! 
            This is a description for helping average users to choose plugins with. 
            Make sure to make the content as easy and clear as possible. 
        !!!
        
        Returns:
            str: Price description of this plugin.
        """
        raise NotImplementedError("Not implemented function")

    
    # service handlers
    # return opencv2 image
    @abc.abstractmethod
    def getResource(self, database, id):
        """
        Retrieve a resource.
        
        Args:
            database (obj): The database instance spawned by server.
            id       (int): ID of the resource.

        Returns:
            object: An OpenCV matrix containing the raw resource.
        """

        raise NotImplementedError("Not implemented function")
    
    # return printable
    @abc.abstractmethod
    def getResourceExtraInfo(self, database, id):
        """
        Retrieve extra info of a resource.
        
        Args:
            database (obj): The database instance spawned by server.
            id       (int): ID of the resource.

        Returns:
            object: An OpenCV matrix containing the raw resource, "None" if failed
        """

        raise NotImplementedError("Not implemented function")

    @abc.abstractmethod
    def putResource(self, database, id, datastream, mime):
        """
        Decide and save a resource.
        
        Args:
            database (obj): The database instance spawned by server.
            id       (int): Global resource generated by module layer.
            datastream (obj): InputStream of a flask's FileStorage instance.
            mime       (str): The MIME-type of the resource.

        Returns:
            bool: True if ok, False if failed.
        """

        raise NotImplementedError("Not implemented function")

