FROM python:3.7-buster

RUN apt update && apt install -y python3-pip
WORKDIR /server/
COPY model_plugins/ ./model_plugins/
COPY photo_loader_plugins/ ./photo_loader_plugins/
COPY *.py ./

RUN pip3 install opencv-python flask psycopg2-binary

CMD python3 main.py